### ISSUE TITLE
User Flow

### ISSUE THREAD

**Issue by MarceloAlves** [MarceloAlves/swrpg-shop#6]
Lets talk about users.

Some thoughts I have.

I think we should take the same route as CodePen/JSBin where a user doesn't have to log in to create a shop. What I'm thinking is they can hit `Create Shop` and pick a few options then roll it. The shop is created and stored for 24 hours or something and then expires.

Where a user login would come into play would be if a person wants to save a shop for later use or they have custom settings for shops. I know the app version has Shop Specializations and you can create ones that have more weapons than armor or they only sell starships/vechiles. Maybe a pay feature would be to unlock unlimited shops or some random stuff.

Another difference could be, once you roll a 24-hour-without-login-shops, that's the shop you get. Users logged in (GM's) could maybe have the option to add specific items to a shop.

A user might have an NPC that always has a shop available. Then they can just quickly load it for other players. Or if inventory changes they can re-roll that NPC's shop. Also before a campaign there could be multiple shops available.

Thoughts?

**Comment by IamVolt** [comment]
I agree, a no sign in shop that generates for 24 hours would work great.

The sign in and create custom shops and save them would also work good for the GMs, specially if you know in your next session maybe the PCs were going to encounter a black market fencer or maybe a junkyard scrapper. Then the GM could create specialty shops specific to those encounters, maybe pick from category of items or just select specific ones.

For all other instances u just enter the info like DUE credits asks and generate.
